const express = require('express')
const controls = require('../controls/userControls')
const route = express.Router()
const validate = require('../middleware/validationRegister')
const limiterLogin = require('../middleware/rateLimoterLogin')
const {verifyTokenAndAdmin} = require('../middleware/verifyToken')
const rateLimit= require('../middleware/rateLimoter')
route.route('/')
    .get(verifyTokenAndAdmin,controls.getAllUsers)
route.route('/login')
    .post(limiterLogin, controls.login)
route.route('/register')
    .post(validate(), controls.register)
route.route('/forgetpassword')
    .post( rateLimit,controls.forgetPassword)
route.route('/resetpassword')
    .post( controls.resetPassword)
route.route('/verifyaccount')
    .post( controls.verifyAccount)
route.route('/resendcode')
    .post( rateLimit,controls.resendCode)
    

module.exports = route